### ISSUE TITLE
测试工具报错

### ISSUE THREAD

**Issue by RMBhu** [zbdba/db-recovery#1]
系统环境	CentOS 7.2 64位  
MySQL版本官方社区办5.7.25 
go版本1.15.5
这是执行命令

> ./bin/db-recovery recovery FromDataFile --DBName="hu" --SysDataFile="/data/3307/data/ibdata1" --TableDataFile="/data/3307/data/hu/t.ibd" --TableName="t" --OpType="RecoveryData"
> ./bin/db-recovery recovery FromRedoFile  --RedoFile="/data/3307/dataib_logfile0"  --SysDataFile="/data/3307/data/ibdata1"  --DBName="hu"  --TableName="t"

报错如下：
E1222 09:56:21.524700   16163 logs.go:89] len is not equal field len, len is  4  field len is  6  i is  1 DB_TRX_ID
E1222 09:56:21.528755   16163 logs.go:89] len is not equal field len, len is  4  field len is  6  i is  2 DB_TRX_ID
E1222 09:56:21.545315   16163 logs.go:89] len is not equal field len, len is  4  field len is  6  i is  2 DB_TRX_ID
E1222 09:56:21.549630   16163 logs.go:89] len is not equal field len, len is  4  field len is  6  i is  2 DB_TRX_ID
panic: runtime error: slice bounds out of range [2:0]

goroutine 1 [running]:
github.com/zbdba/db-recovery/recovery/ibdata.SliceInsert(...)
        /usr/local/db-recovery/recovery/ibdata/parse_ib.go:208
github.com/zbdba/db-recovery/recovery/ibdata.(*ParseIB).AddInternalColumns(0xc0000a9d68)
        /usr/local/db-recovery/recovery/ibdata/parse_ib.go:267 +0x15a5
github.com/zbdba/db-recovery/recovery/ibdata.(*ParseIB).ParseDictPage(0xc0000a9d68, 0x7fffe6fda568, 0x17, 0x5, 0x0)
        /usr/local/db-recovery/recovery/ibdata/parse_ib.go:625 +0x6f8
github.com/zbdba/db-recovery/recovery/client.FromDataFile(0xc00008a580, 0xc0000601e0, 0x0, 0x5)
        /usr/local/db-recovery/recovery/client/command.go:104 +0x13b
github.com/spf13/cobra.(*Command).execute(0xc00008a580, 0xc000060190, 0x5, 0x5, 0xc00008a580, 0xc000060190)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc00008a000, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/zbdba/db-recovery/recovery/client.Main()
        /usr/local/db-recovery/recovery/client/client.go:37 +0x2d
main.main()
        /usr/local/db-recovery/cmd/recovery/main.go:20 +0x25

**Comment by zbdba** [comment]
看起来是解析数据字典的时候有些问题，方便的话把你的相关文件上传到百度网盘或者其他能下载的地方，我调试看看。

**Comment by RMBhu** [comment]
您好，相关文件已经上传到百度网盘，这是链接: https://pan.baidu.com/s/1TwUqMYy-3Wx7W0WccBbARQ 提取码: n32n
